#**Unsupervised Learning**

In [ ]:

import pandas as pd
import numpy as np
import random
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import silhouette_score
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [ ]:
df=pd.read_csv("seeds - seeds.csv")
df.head()

,ID,area,perimeter,compactness,lengthOfKernel,widthOfKernel,asymmetryCoefficient,lengthOfKernelGroove,seedType
0,1,15.26,14.84,0.8710,5.763,3.312,2.221,5.220,1
1,2,14.88,14.57,0.8811,5.554,3.333,1.018,4.956,1
2,3,14.29,14.09,0.9050,5.291,3.337,2.699,4.825,1
3,4,13.84,13.94,0.8955,5.324,3.379,2.259,4.805,1
4,5,16.14,14.99,0.9034,5.658,3.562,1.355,5.175,1

In [ ]:
remove = ['ID','seedType']
new_df = df[df.columns.difference(remove)]
new_df.head()

,area,asymmetryCoefficient,compactness,lengthOfKernel,lengthOfKernelGroove,perimeter,widthOfKernel
0,15.26,2.221,0.8710,5.763,5.220,14.84,3.312
1,14.88,1.018,0.8811,5.554,4.956,14.57,3.333
2,14.29,2.699,0.9050,5.291,4.825,14.09,3.337
3,13.84,2.259,0.8955,5.324,4.805,13.94,3.379
4,16.14,1.355,0.9034,5.658,5.175,14.99,3.562

In [ ]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
scaled_data = scalar.fit_transform(new_df)
pd.DataFrame(scaled_data).head(2)

          0         1         2         3         4         5         6
0  0.142098 -0.986152  0.000061  0.304218 -0.383577  0.215462  0.141702
1  0.011188 -1.788166  0.428515 -0.168625 -0.922013  0.008224  0.197432

In [ ]:
from sklearn.metrics import silhouette_score

model=KMeans(n_clusters=5,random_state=1)
kmeans = model.fit(scaled_data)
cluster_preds=model.fit_predict(scaled_data)
labels = kmeans.labels_
score=silhouette_score(scaled_data,labels,metric='euclidean')
print("Silhouette_score for clusters is", score)

Silhouette_score for clusters is 0.28619742240883067

In [ ]:
from sklearn.datasets import load_iris

x , y = load_iris(return_X_y=True)
pd.DataFrame(x).head()

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [ ]:
scaled_data = scalar.fit_transform(x)
pd.DataFrame(scaled_data).head()

          0         1         2         3
0 -0.900681  1.019004 -1.340227 -1.315444
1 -1.143017 -0.131979 -1.340227 -1.315444
2 -1.385353  0.328414 -1.397064 -1.315444
3 -1.506521  0.098217 -1.283389 -1.315444
4 -1.021849  1.249201 -1.340227 -1.315444

In [ ]:
model = KMeans(n_clusters=2,random_state=1)
kmeans = model.fit(scaled_data)
cluster_preds = model.fit_predict(scaled_data)
labels = kmeans.labels_
score=silhouette_score(scaled_data,labels,metric='euclidean')
print("Silhouette_score for clusters is", score)

Silhouette_score for clusters is 0.5817500491982808